import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Products from "./components/Products";
import SoyWaxSection from "./components/SoyWaxSection";
import Testimonial from "./components/Testimonial";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["Latin"],
  display: "swap",
});
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["Latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "candle leaf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${poppins.className}`}>
        <Header />
        {children}
        <Products />
        <SoyWaxSection />
        <Testimonial />
        <Footer />
      </body>
    </html>
  );
}
